CREATE TABLE IF NOT EXISTS songs(
	id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	artist TEXT,
	title TEXT,
	year TEXT
);
CREATE TABLE IF NOT EXISTS artist_count(
	id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	artist TEXT,
	occurence int
);
CREATE TABLE IF NOT EXISTS songs_count(
	id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	title TEXT,
	occurence int
);
CREATE TABLE IF NOT EXISTS report(
	id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	title TEXT,
	artist TEXT,
	duration int,
	occurence int
);